const pages=[...document.querySelectorAll('.page')];
const navButtons=[...document.querySelectorAll('.bottom-nav button')];
const toast=document.querySelector('#toast');
let tasks=(()=>{try{const saved=JSON.parse(localStorage.getItem('lumiere-tasks')||'[]');return Array.isArray(saved)?saved:[]}catch{return[]}})();
if('scrollRestoration' in history)history.scrollRestoration='manual';window.scrollTo(0,0);pages.forEach(page=>page.scrollTop=0);
const homePage=document.querySelector('[data-page="home"]');let homePan=null;homePage.addEventListener('touchstart',event=>{if(event.touches.length!==1){homePan=null;return}const touch=event.touches[0];homePan={x:touch.clientX,y:touch.clientY}},{passive:true});homePage.addEventListener('touchmove',event=>{if(!homePan||event.touches.length!==1)return;const touch=event.touches[0];const dx=touch.clientX-homePan.x;const dy=touch.clientY-homePan.y;if(Math.abs(dx)>10&&Math.abs(dx)>Math.abs(dy)*1.2)event.preventDefault()},{passive:false});homePage.addEventListener('touchend',()=>homePan=null,{passive:true});homePage.addEventListener('touchcancel',()=>homePan=null,{passive:true});

const splashScreen=document.querySelector('#splash-screen');
function runSplashScreen(){const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced)splashScreen.classList.add('reduced');setTimeout(()=>{splashScreen.classList.add('finished');setTimeout(()=>splashScreen.remove(),800)},reduced?900:5000)}
runSplashScreen();

function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),1500)}
function switchPage(target){pages.forEach(p=>p.classList.toggle('active',p.dataset.page===target));navButtons.forEach(b=>b.classList.toggle('active',b.dataset.target===target));document.querySelector('.app-shell').classList.toggle('chat-page',target==='chat');document.querySelector(`[data-page="${target}"]`).scrollTop=0;if(target==='chat')requestAnimationFrame(()=>window.LumiereChatScrollToEnd?.())}
window.LumiereSwitchPage=switchPage;
navButtons.forEach(button=>button.addEventListener('click',()=>switchPage(button.dataset.target)));

function saveTasks(){localStorage.setItem('lumiere-tasks',JSON.stringify(tasks))}
function renderTasks(){const list=document.querySelector('#task-list');list.innerHTML='';if(!tasks.length){list.innerHTML='<p class="task-empty">还没有待办，添加后只会显示你自己的内容。</p>'}tasks.forEach((task,index)=>{const item=typeof task==='string'?{text:task,done:false}:task;const label=document.createElement('label');label.className='task';label.innerHTML=`<input type="checkbox" data-index="${index}"${item.done?' checked':''}><span class="checkmark"></span><span></span><button type="button" class="task-delete" aria-label="删除待办">×</button>`;label.querySelector('span:nth-of-type(2)').textContent=item.text;label.querySelector('input').addEventListener('change',e=>{tasks[index]={...item,done:e.target.checked};saveTasks();renderTasks()});label.querySelector('.task-delete').addEventListener('click',()=>{tasks.splice(index,1);saveTasks();renderTasks();showToast('待办已删除')});list.append(label)});document.querySelector('#task-count').textContent=`${tasks.filter(task=>!(typeof task==='string'?false:task.done)).length} 件`}
renderTasks();
document.querySelector('#task-form').addEventListener('submit',e=>{e.preventDefault();const input=document.querySelector('#task-input');if(!input.value.trim())return;tasks.push({text:input.value.trim(),done:false});saveTasks();input.value='';renderTasks();showToast('已加入今天的清单')});

document.querySelector('#model-select').addEventListener('change',e=>{document.querySelector('#header-model-name').textContent=e.target.value;showToast(`已切换至 ${e.target.value}`)});
const chatNameDisplay=document.querySelector('#chat-name-display');const chatNameInput=document.querySelector('#chat-name-input');const defaultChatName='LUMIÈRE';chatNameDisplay.textContent=localStorage.getItem('lumiere-chat-name')||defaultChatName;function editChatName(){chatNameInput.value=chatNameDisplay.textContent;chatNameDisplay.hidden=true;chatNameInput.hidden=false;chatNameInput.focus();chatNameInput.select()}function saveChatName(cancel=false){if(chatNameInput.hidden)return;const value=cancel?chatNameDisplay.textContent:(chatNameInput.value.trim()||defaultChatName);chatNameDisplay.textContent=value;if(!cancel)localStorage.setItem('lumiere-chat-name',value);chatNameInput.hidden=true;chatNameDisplay.hidden=false;if(!cancel)showToast('聊天页名称已保存')}chatNameDisplay.addEventListener('click',editChatName);chatNameInput.addEventListener('blur',()=>saveChatName());chatNameInput.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();saveChatName()}if(event.key==='Escape'){event.preventDefault();saveChatName(true)}});
const chatDrawer=document.querySelector('#chat-drawer');const drawerBackdrop=document.querySelector('#drawer-backdrop');
function toggleChatDrawer(open){chatDrawer.classList.toggle('open',open);drawerBackdrop.classList.toggle('open',open);chatDrawer.setAttribute('aria-hidden',!open);drawerBackdrop.setAttribute('aria-hidden',!open)}
document.querySelector('#chat-menu-button').addEventListener('click',()=>toggleChatDrawer(true));document.querySelector('#drawer-close').addEventListener('click',()=>toggleChatDrawer(false));drawerBackdrop.addEventListener('click',()=>toggleChatDrawer(false));
const drawerSearch=document.querySelector('#drawer-search-input');function filterChatHistory(){const keyword=drawerSearch.value.trim().toLowerCase();let visible=0;document.querySelectorAll('.conversation-history button').forEach(button=>{const match=button.textContent.toLowerCase().includes(keyword);button.hidden=!match;if(match)visible++});document.querySelectorAll('.history-group').forEach(group=>group.hidden=![...group.querySelectorAll('button')].some(button=>!button.hidden));document.querySelector('#search-empty').hidden=visible>0}drawerSearch.addEventListener('input',filterChatHistory);document.querySelector('#drawer-search-clear').addEventListener('click',()=>{drawerSearch.value='';filterChatHistory();drawerSearch.focus()});
document.querySelector('#temporary-chat-toggle').addEventListener('change',event=>showToast(event.target.checked?'临时对话已开启':'临时对话已关闭'));
let drawerTouchStart=0;chatDrawer.addEventListener('touchstart',event=>drawerTouchStart=event.touches[0].clientX,{passive:true});chatDrawer.addEventListener('touchend',event=>{if(event.changedTouches[0].clientX-drawerTouchStart<-60)toggleChatDrawer(false)},{passive:true});
const chatPage=document.querySelector('[data-page="chat"]');let chatSwipe=null;chatPage.addEventListener('touchstart',event=>{if(chatDrawer.classList.contains('open')||event.touches.length!==1){chatSwipe=null;return}const touch=event.touches[0];chatSwipe={x:touch.clientX,y:touch.clientY,time:Date.now()}},{passive:true});chatPage.addEventListener('touchend',event=>{if(!chatSwipe)return;const touch=event.changedTouches[0];const dx=touch.clientX-chatSwipe.x;const dy=touch.clientY-chatSwipe.y;const elapsed=Date.now()-chatSwipe.time;chatSwipe=null;if(dx>85&&Math.abs(dy)<55&&dx>Math.abs(dy)*1.5&&elapsed<900){toggleChatDrawer(false);switchPage('home');showToast('已返回主页')}},{passive:true});
const conversationScroller=document.querySelector('#conversation');const scrollToBottomButton=document.querySelector('#scroll-to-bottom');function updateScrollToBottom(){const distance=conversationScroller.scrollHeight-conversationScroller.scrollTop-conversationScroller.clientHeight;scrollToBottomButton.classList.toggle('visible',distance>180)}conversationScroller.addEventListener('scroll',updateScrollToBottom,{passive:true});scrollToBottomButton.addEventListener('click',()=>conversationScroller.scrollTo({top:conversationScroller.scrollHeight,behavior:'smooth'}));
document.querySelector('#chat-form').addEventListener('submit',e=>e.preventDefault());

const voiceButton=document.querySelector('#voice-button');const chatInput=document.querySelector('#chat-input');const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;let recognition=null;let isListening=false;
const visualViewport=window.visualViewport;function syncChatKeyboard(){const shell=document.querySelector('.app-shell');const focused=document.activeElement===chatInput;if(!visualViewport||!focused){shell.classList.remove('chat-keyboard-open');shell.style.removeProperty('--chat-viewport-height');shell.style.removeProperty('--chat-viewport-top');return}shell.classList.add('chat-keyboard-open');shell.style.setProperty('--chat-viewport-height',`${visualViewport.height}px`);shell.style.setProperty('--chat-viewport-top',`${visualViewport.offsetTop}px`);requestAnimationFrame(()=>window.LumiereChatScrollToEnd?.('auto'))}chatInput.addEventListener('focus',()=>{syncChatKeyboard();setTimeout(syncChatKeyboard,120);setTimeout(syncChatKeyboard,320)});chatInput.addEventListener('blur',()=>setTimeout(syncChatKeyboard,120));visualViewport?.addEventListener('resize',syncChatKeyboard);visualViewport?.addEventListener('scroll',syncChatKeyboard);
function setListening(active){isListening=active;voiceButton.classList.toggle('listening',active);voiceButton.setAttribute('aria-pressed',active);voiceButton.setAttribute('aria-label',active?'停止语音输入':'开始语音输入');chatInput.placeholder=active?'正在聆听，请开始说话…':'写下想说的话…'}
if(SpeechRecognition){recognition=new SpeechRecognition();recognition.lang='zh-CN';recognition.continuous=false;recognition.interimResults=true;let originalText='';recognition.onstart=()=>{originalText=chatInput.value.trim();setListening(true);showToast('正在聆听…')};recognition.onresult=event=>{let transcript='';for(let i=event.resultIndex;i<event.results.length;i++)transcript+=event.results[i][0].transcript;chatInput.value=[originalText,transcript].filter(Boolean).join(originalText?' ':'')};recognition.onerror=event=>{setListening(false);showToast(event.error==='not-allowed'?'请允许浏览器使用麦克风':'没有听清，请再试一次')};recognition.onend=()=>{if(isListening){setListening(false);showToast(chatInput.value.trim()?'语音已转成文字':'语音输入已结束')}}}
voiceButton.addEventListener('click',()=>{if(!recognition)return showToast('当前浏览器不支持语音输入');if(isListening)recognition.stop();else{try{recognition.start()}catch(error){setListening(false)}}});

const attachmentTrigger=document.querySelector('#attachment-trigger');const attachmentSheet=document.querySelector('#attachment-sheet');
function toggleAttachmentSheet(open){attachmentSheet.classList.toggle('open',open);attachmentSheet.setAttribute('aria-hidden',!open);attachmentTrigger.setAttribute('aria-expanded',open);attachmentTrigger.classList.toggle('active',open)}
attachmentTrigger.addEventListener('click',()=>toggleAttachmentSheet(!attachmentSheet.classList.contains('open')));
document.querySelector('[data-attachment="image"]').addEventListener('click',()=>document.querySelector('#image-attachment-input').click());document.querySelector('[data-attachment="file"]').addEventListener('click',()=>document.querySelector('#file-attachment-input').click());document.querySelector('[data-attachment="camera"]').addEventListener('click',()=>document.querySelector('#camera-attachment-input').click());
let pendingAttachments=[];
function renderPendingAttachments(){let tray=document.querySelector('#pending-attachments');if(!tray){tray=document.createElement('div');tray.id='pending-attachments';tray.className='pending-attachments';document.querySelector('#chat-form').prepend(tray)}tray.replaceChildren(...pendingAttachments.map((item,index)=>{const chip=document.createElement('span');chip.className='attachment-chip';chip.textContent=item.name;const remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.setAttribute('aria-label','移除附件');remove.onclick=()=>{pendingAttachments.splice(index,1);renderPendingAttachments()};chip.append(remove);return chip}))}
function appendAttachment(file){if(!file)return;if(file.size>5*1024*1024)return showToast('附件需小于 5MB');if(pendingAttachments.length>=3)return showToast('一次最多发送 3 个附件');const reader=new FileReader();reader.onload=()=>{pendingAttachments.push({name:file.name||'附件',type:file.type||'application/octet-stream',size:file.size,data:String(reader.result).split(',')[1]||''});renderPendingAttachments();toggleAttachmentSheet(false);showToast('附件已添加，点击发送后 AI 才会收到')};reader.onerror=()=>showToast('附件读取失败');reader.readAsDataURL(file)}
window.LumiereAttachments={take(){const items=pendingAttachments;pendingAttachments=[];renderPendingAttachments();return items},peek(){return pendingAttachments.slice()},restore(items){pendingAttachments=[...items,...pendingAttachments];renderPendingAttachments()}};
document.querySelector('#image-attachment-input').addEventListener('change',event=>{appendAttachment(event.target.files[0]);event.target.value=''});document.querySelector('#camera-attachment-input').addEventListener('change',event=>{appendAttachment(event.target.files[0]);event.target.value=''});document.querySelector('#file-attachment-input').addEventListener('change',event=>{appendAttachment(event.target.files[0]);event.target.value=''});

document.querySelectorAll('.setting-row button,.profile-card button').forEach(button=>button.addEventListener('click',()=>showToast('这是可继续扩展的设置项')));
document.querySelectorAll('.switch').forEach(toggle=>toggle.addEventListener('change',()=>showToast(toggle.checked?'已开启':'已关闭')));

const shell=document.querySelector('.app-shell');
const assetStore=(()=>{let pending;function db(){if(!pending)pending=new Promise((resolve,reject)=>{const request=indexedDB.open('lumiere-personal-assets',1);request.onupgradeneeded=()=>request.result.createObjectStore('assets');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});return pending}async function run(mode,action){const database=await db();return new Promise((resolve,reject)=>{const transaction=database.transaction('assets',mode);const request=action(transaction.objectStore('assets'));request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}return{get:key=>run('readonly',store=>store.get(key)),set:(key,value)=>run('readwrite',store=>store.put(value,key)),remove:key=>run('readwrite',store=>store.delete(key))}})();
function applySavedBackground(data){if(!data)return;const image=`url("${data}")`;shell.style.setProperty('--user-background',image);shell.classList.add('has-custom-background');document.querySelector('#background-preview').style.backgroundImage=`linear-gradient(90deg,rgba(255,255,255,.48),rgba(255,255,255,.1)),${image}`}
function applySavedAvatar(person,data){if(!data)return;shell.style.setProperty(`--${person}-avatar-image`,`url("${data}")`);shell.classList.add(`has-${person}-avatar`)}
async function restorePersonalAssets(){try{const [background,lumiAvatar,userAvatar]=await Promise.all([assetStore.get('background'),assetStore.get('avatar-lumi'),assetStore.get('avatar-user')]);applySavedBackground(background);applySavedAvatar('lumi',lumiAvatar);applySavedAvatar('user',userAvatar)}catch(error){console.warn('Could not restore personal images',error)}}
restorePersonalAssets();
const relationshipStartUtc=Date.UTC(2026,5,27);
function renderBondDays(){const now=new Date();const todayUtc=Date.UTC(now.getFullYear(),now.getMonth(),now.getDate());const days=Math.max(1,Math.floor((todayUtc-relationshipStartUtc)/86400000)+1);document.querySelector('#bond-days').textContent=days;document.querySelector('#drawer-bond-days').textContent=`相伴 ${days} 天`}
renderBondDays();setInterval(renderBondDays,60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)renderBondDays()});
const themeNames={atlantic:'大西洋',sintra:'辛特拉',lime:'青柠软糖',dew:'奶油晨露',nebula:'棉花糖星云'};
const appearancePanel=document.querySelector('.appearance-panel');appearancePanel.insertAdjacentHTML('afterbegin','<label class="style-control"><span><b>界面风格</b><small>切换纸感手账，不影响原主题设置</small></span><input id="journal-style-toggle" type="checkbox" class="switch" /></label>');
const journalStyleToggle=document.querySelector('#journal-style-toggle');function applyInterfaceStyle(style){const selected=style==='journal'?'journal':'glass';shell.dataset.style=selected;journalStyleToggle.checked=selected==='journal';localStorage.setItem('lumiere-interface-style',selected)}journalStyleToggle.addEventListener('change',()=>{applyInterfaceStyle(journalStyleToggle.checked?'journal':'glass');showToast(journalStyleToggle.checked?'纸感手账已开启':'已恢复原版界面')});applyInterfaceStyle(localStorage.getItem('lumiere-interface-style')||'glass');
function applyTheme(theme){const selected=themeNames[theme]?theme:'atlantic';shell.dataset.theme=selected;document.querySelector('#theme-name').textContent=themeNames[selected];document.querySelectorAll('.theme-option').forEach(button=>{const active=button.dataset.theme===selected;button.classList.toggle('active',active);button.setAttribute('aria-checked',active)});localStorage.setItem('lumiere-theme',selected)}
document.querySelectorAll('.theme-option').forEach(button=>button.addEventListener('click',()=>{applyTheme(button.dataset.theme);showToast(`已切换为${themeNames[button.dataset.theme]}主题`)}));
const nightToggle=document.querySelector('#night-toggle');
function applyNightMode(enabled){shell.dataset.mode=enabled?'dark':'light';nightToggle.checked=enabled;const surfaceColor=enabled?'#111822':'#dcebf5';document.documentElement.style.backgroundColor=surfaceColor;document.body.style.backgroundColor=surfaceColor;document.querySelector('meta[name="theme-color"]').setAttribute('content',surfaceColor);localStorage.setItem('lumiere-night',enabled?'1':'0')}
nightToggle.addEventListener('change',()=>{applyNightMode(nightToggle.checked);showToast(nightToggle.checked?'夜间模式已开启':'夜间模式已关闭')});
applyTheme(localStorage.getItem('lumiere-theme')||'atlantic');applyNightMode(localStorage.getItem('lumiere-night')==='1');
function setVisualControl(inputId,outputId,variable,format){const input=document.querySelector(inputId);const output=document.querySelector(outputId);const apply=()=>{const value=input.value;shell.style.setProperty(variable,format(value));output.textContent=format(value);localStorage.setItem(input.id,value)};const saved=localStorage.getItem(input.id);if(saved!==null)input.value=saved;input.addEventListener('input',apply);apply()}
setVisualControl('#blur-range','#blur-output','--custom-blur',value=>`${value}px`);
setVisualControl('#opacity-range','#opacity-output','--custom-opacity',value=>{shell.style.setProperty('--custom-opacity-number',value/100);return `${value}%`});
setVisualControl('#message-opacity-range','#message-opacity-output','--message-opacity-label',value=>{shell.style.setProperty('--message-opacity',value/100);return `${value}%`});
document.querySelector('#background-input').addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;if(!file.type.startsWith('image/'))return showToast('请选择图片文件');const reader=new FileReader();reader.onload=async()=>{applySavedBackground(reader.result);try{await assetStore.set('background',reader.result);showToast('背景已更换并保存')}catch{showToast('背景已更换，但浏览器未能保存')}};reader.readAsDataURL(file)});
document.querySelector('#reset-background').addEventListener('click',async()=>{shell.classList.remove('has-custom-background');shell.style.removeProperty('--user-background');document.querySelector('#background-preview').style.backgroundImage='';document.querySelector('#background-input').value='';try{await assetStore.remove('background')}catch{}showToast('已恢复默认背景')});

function bindAvatarUpload(inputSelector,person,label){document.querySelector(inputSelector).addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;if(!file.type.startsWith('image/'))return showToast('请选择图片文件');const reader=new FileReader();reader.onload=async()=>{applySavedAvatar(person,reader.result);try{await assetStore.set(`avatar-${person}`,reader.result);showToast(`${label}已更换并保存`)}catch{showToast(`${label}已更换，但浏览器未能保存`)}};reader.readAsDataURL(file)})}
bindAvatarUpload('#lumi-avatar-input','lumi','Lumi 头像');
bindAvatarUpload('#user-avatar-input','user','我的头像');

const heroCopyDefaults={title:'我们又一起收藏了一天',subtitle:'那些微小的心情，也值得被认真记住。'};
const heroTitle=document.querySelector('#hero-title');const heroSubtitle=document.querySelector('#hero-subtitle');const heroEditor=document.querySelector('#hero-copy-editor');const heroTitleInput=document.querySelector('#hero-title-input');const heroSubtitleInput=document.querySelector('#hero-subtitle-input');
function loadHeroCopy(){heroTitle.textContent=localStorage.getItem('lumiere-hero-title')||heroCopyDefaults.title;heroSubtitle.textContent=localStorage.getItem('lumiere-hero-subtitle')||heroCopyDefaults.subtitle}
function toggleHeroEditor(open,focusTarget='title'){heroEditor.hidden=!open;if(open){heroTitleInput.value=heroTitle.textContent;heroSubtitleInput.value=heroSubtitle.textContent;(focusTarget==='subtitle'?heroSubtitleInput:heroTitleInput).focus()}}
heroTitle.addEventListener('dblclick',()=>toggleHeroEditor(true,'title'));heroSubtitle.addEventListener('dblclick',()=>toggleHeroEditor(true,'subtitle'));document.querySelector('#hero-edit-cancel').addEventListener('click',()=>toggleHeroEditor(false));heroEditor.addEventListener('submit',event=>{event.preventDefault();const title=heroTitleInput.value.trim()||heroCopyDefaults.title;const subtitle=heroSubtitleInput.value.trim()||heroCopyDefaults.subtitle;heroTitle.textContent=title;heroSubtitle.textContent=subtitle;localStorage.setItem('lumiere-hero-title',title);localStorage.setItem('lumiere-hero-subtitle',subtitle);toggleHeroEditor(false);showToast('主页文案已保存')});loadHeroCopy();
