create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  name text not null default '新的对话' check (char_length(name) <= 80),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.sessions(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'tool')),
  content text not null,
  reasoning_content text,
  visible boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists messages_session_visible_id_idx on public.messages(session_id, visible, id);

create table if not exists public.memories (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.sessions(id) on delete cascade,
  summary text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists memories_session_id_idx on public.memories(session_id, id desc);

create table if not exists public.settings (
  id smallint primary key default 1 check (id = 1),
  system_prompt text not null,
  temperature real not null default 0.8 check (temperature between 0 and 2),
  max_context_rounds integer not null default 20 check (max_context_rounds between 1 and 100),
  max_context_tokens integer not null default 12000 check (max_context_tokens between 1000 and 1000000),
  compress_threshold integer not null default 9000 check (compress_threshold between 500 and 1000000),
  compress_keep_rounds integer not null default 6 check (compress_keep_rounds between 1 and 50),
  max_reply_tokens integer not null default 1200 check (max_reply_tokens between 64 and 100000),
  updated_at timestamptz not null default now()
);
insert into public.settings (id, system_prompt) values (1, '你是 Lumière，一位温柔、真诚且尊重边界的长期陪伴者。先理解对方，再简洁回应；不要假装拥有现实世界的身体或经历。') on conflict (id) do nothing;

alter table public.sessions enable row level security;
alter table public.messages enable row level security;
alter table public.memories enable row level security;
alter table public.settings enable row level security;
-- No public policies are created. Only the backend service-role key can access these tables.

grant usage on schema public to service_role;
grant select, insert, update, delete on table
  public.sessions,
  public.messages,
  public.memories,
  public.settings
to service_role;
grant usage, select on all sequences in schema public to service_role;
